### ISSUE TITLE
Take the Docs out of the Controller

### ISSUE THREAD

**Issue by schmijos** [richhollis/swagger-docs#113] opened 2015-05-06 09:32 UTC
I don't like having all the *swagger-docs* DSL inside the controllers. Would it be possible to extract the docs into separate files? A proposal would be to use them "magically" like that:

```ruby
# app/controllers/some_controller.rb
class SomeController < SomeBaseController
  has_swagger_docs if Rails.env.docs?

  ....
end
```

The method *has_swagger_docs* would then automatically search for a file named after some convention to be defined. It would contain what is currently the DSL in the controller files:

```ruby
# docs/swagger/some_controller_docs.rb
swagger_controller :some, "Some Resource"

swagger_api :index do
  ...
end
```

I tried to implement this extension by myself, but I think I'm not experienced enough with ruby meta-programming.

**Comment by vmpj** [comment] 2015-05-12 06:41
I also like that idea. But I just worried that splitting the code and the docs will cause them to go out of sync more easily.

**Comment by schmijos** [comment] 2015-05-13 07:47
What about including it into the controller in a way the IDE supports? For example like that:

```ruby
# app/controllers/some_controller.rb
class SomeController < SomeBaseController
  include SwaggerDocs::SomeController if Rails.env.docs?

  ....
end
```

Like that the IDE will guide you to the correct file.

**Comment by mansoorelahi** [comment] 2015-05-22 11:34
+1 for taking docs out of controller

**Comment by krevels** [comment] 2015-05-27 22:08
This may qualify as an abuse of concerns, but it seems to work:

```ruby
# app/controllers/concerns/swagger_docs/books.rb
# The SwaggerDocs namespace isn't required here, but I prefer using it for separation from my other "concerns"
module SwaggerDocs::Books
  extend ActiveSupport::Concern

  included do
    swagger_controller :books, "Book Management"
   
    swagger_api :index do
      # blah blah
    end

     # etc
  end
end
```

Then my controller only contains:
```ruby
# app/controllers/books_controller.rb
class BookController < BaseController
  include SwaggerDocs::Books
end
```

**Comment by schmijos** [comment] 2015-05-28 16:12
I already tried some thing like that. But it doesn't work with concerns:

```ruby
# app/controllers/giscockpit/api/v1/support/geographic_controller.rb
module Giscockpit
  class Api::V1::Support::GeographicController < Giscockpit::Api::ApplicationController
    include SwaggerDocs::Api::V1::Support::Geographic
    
    # ...
```

and 

```ruby
# app/controllers/giscockpit/concerns/swagger_docs/api/v1/support/geographic.rb
module SwaggerDocs::Api::V1::Support::Geographic
  extend ActiveSupport::Concern

  included do
    swagger_controller :geographic, 'Geographic'

    swagger_api :gach do
      # ...
    end
  end
end
```

But it does work if I put the DSL part into the controller itself. As `api_base_controller` I've configured `Giscockpit::Api::ApplicationController`.

**Comment by richhollis** [comment] 2016-01-13 11:38
Closing as swagger-docs was designed to generate from the controllers.

**Closed by richhollis** 2016-01-13 11:38 UTC

**Comment by kigonya** [comment] 2016-12-21 19:23
Been looking for solution as well since my controllers were getting messy. krevels's direction worked for me.

**Comment by nishant3150** [comment] 2017-06-09 05:56
@richhollis Can you please suggest some workaround if available for this. Cause for Rails controllers are getting over crowded with swagger code.

**Comment by atiftechverx** [comment] 2019-10-22 14:51
krevels's  solution worked.
